[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install --only-binary=:all: -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm ci --legacy-peer-deps || npm install --legacy-peer-deps",
  "cd frontend && npm run build",
  "cd .."
]

[start]
cmd = "gunicorn --config gunicorn.conf.py app:app"
