[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "gunicorn --config gunicorn.conf.py app:app"
