[build]
builder = "nixpacks"

[build.env]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[[build.command]]
cmd = "bash build.sh"

[deploy]
startCommand = "gunicorn --config gunicorn.conf.py app:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
