services:
  - type: web
    name: car-price-predictor
    env: python
    region: oregon
    buildCommand: "bash render-build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
